In [1]:
# To Check the Missing values

In [2]:
import pandas as pd
import numpy as np

In [3]:
# upload all the tables
customers = pd.read_csv(r"C:\Users\acer\Documents\Venkat Document\Project\Cart2Insights\Data\Raw\olist_customers_dataset.csv")
Order_Items=pd.read_csv(r"C:\Users\acer\Documents\Venkat Document\Project\Cart2Insights\Data\Raw\olist_order_items_dataset.csv")
Products=pd.read_csv(r"C:\Users\acer\Documents\Venkat Document\Project\Cart2Insights\Data\Raw\olist_products_dataset.csv")
Sellers=pd.read_csv(r"C:\Users\acer\Documents\Venkat Document\Project\Cart2Insights\Data\Raw\olist_sellers_dataset.csv")
Payments=pd.read_csv(r"C:\Users\acer\Documents\Venkat Document\Project\Cart2Insights\Data\Raw\olist_order_payments_dataset.csv")
Orders=pd.read_csv(r"C:\Users\acer\Documents\Venkat Document\Project\Cart2Insights\Data\Raw\olist_orders_dataset.csv")
Reviews=pd.read_csv(r"C:\Users\acer\Documents\Venkat Document\Project\Cart2Insights\Data\Raw\olist_order_reviews_dataset.csv")
GeoLocations=pd.read_csv(r"C:\Users\acer\Documents\Venkat Document\Project\Cart2Insights\Data\Raw\olist_geolocation_dataset.csv")
Product_category_name_translation=pd.read_csv(r"C:\Users\acer\Documents\Venkat Document\Project\Cart2Insights\Data\Raw\product_category_name_translation.csv")

In [4]:
# to find the null values 
customers.isnull().sum()

customer_id                 0
customer_unique_id          0
customer_zip_code_prefix    0
customer_city               0
customer_state              0
dtype: int64

In [5]:
Order_Items.isnull().sum()

order_id               0
order_item_id          0
product_id             0
seller_id              0
shipping_limit_date    0
price                  0
freight_value          0
dtype: int64

In [6]:
Products.isnull().sum()

product_id                      0
product_category_name         610
product_name_lenght           610
product_description_lenght    610
product_photos_qty            610
product_weight_g                2
product_length_cm               2
product_height_cm               2
product_width_cm                2
dtype: int64

In [7]:
Sellers.isnull().sum()

seller_id                 0
seller_zip_code_prefix    0
seller_city               0
seller_state              0
dtype: int64

In [8]:
Payments.isnull().sum()

order_id                0
payment_sequential      0
payment_type            0
payment_installments    0
payment_value           0
dtype: int64

In [9]:
Orders.isnull().sum()

order_id                            0
customer_id                         0
order_status                        0
order_purchase_timestamp            0
order_approved_at                 160
order_delivered_carrier_date     1783
order_delivered_customer_date    2965
order_estimated_delivery_date       0
dtype: int64

In [10]:
Reviews.isnull().sum()

review_id                      0
order_id                       0
review_score                   0
review_comment_title       87656
review_comment_message     58247
review_creation_date           0
review_answer_timestamp        0
dtype: int64

In [11]:
GeoLocations.isnull().sum()

geolocation_zip_code_prefix    0
geolocation_lat                0
geolocation_lng                0
geolocation_city               0
geolocation_state              0
dtype: int64

In [12]:
Product_category_name_translation.isnull().sum()

product_category_name            0
product_category_name_english    0
dtype: int64

In [13]:
customers .duplicated().sum()

np.int64(0)

In [14]:
Order_Items.duplicated().sum()

np.int64(0)

In [15]:
Products.duplicated().sum()

np.int64(0)

In [16]:
Sellers.duplicated().sum()

np.int64(0)

In [17]:
Payments.duplicated().sum()

np.int64(0)

In [18]:
Orders.duplicated().sum()

np.int64(0)

In [19]:
Reviews.duplicated().sum()

np.int64(0)

In [20]:
GeoLocations.duplicated().sum()

np.int64(261831)

In [21]:
Product_category_name_translation.duplicated().sum()

np.int64(0)

In [22]:
GeoLocations.loc[GeoLocations.duplicated]

,geolocation_zip_code_prefix,geolocation_lat,geolocation_lng,geolocation_city,geolocation_state
15,1046,-23.546081,-46.644820,sao paulo,SP
44,1046,-23.546081,-46.644820,sao paulo,SP
65,1046,-23.546081,-46.644820,sao paulo,SP
66,1009,-23.546935,-46.636588,sao paulo,SP
67,1046,-23.546081,-46.644820,sao paulo,SP
...,...,...,...,...,...
1000153,99970,-28.343273,-51.873734,ciriaco,RS
1000154,99950,-28.070493,-52.011342,tapejara,RS
1000159,99900,-27.877125,-52.224882,getulio vargas,RS
1000160,99950,-28.071855,-52.014716,tapejara,RS
1000162,99950,-28.070104,-52.018658,tapejara,RS

In [23]:
customers["customer_id"].nunique()

99441

In [24]:
customers.shape

(99441, 5)

In [25]:
print(Orders["order_id"].nunique())
print('Shape:', Orders.shape)

99441
Shape: (99441, 8)

In [26]:
print(Products["product_id"].nunique())
print('Shape:', Products.shape)

32951
Shape: (32951, 9)

In [27]:
print(Sellers["seller_id"].nunique())
print('Shape:', Sellers.shape)

3095
Shape: (3095, 4)

In [29]:
Orders[
    [
        "order_purchase_timestamp",
        "order_approved_at",
        "order_delivered_carrier_date",
        "order_delivered_customer_date",
        "order_estimated_delivery_date"
    ]
].head()

,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
0,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00
1,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13 00:00:00
2,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04 00:00:00
3,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15 00:00:00
4,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26 00:00:00

In [33]:
Order_Items[
    ["price", "freight_value"]
].describe()

               price  freight_value
count  112650.000000  112650.000000
mean      120.653739      19.990320
std       183.633928      15.806405
min         0.850000       0.000000
25%        39.900000      13.080000
50%        74.990000      16.260000
75%       134.900000      21.150000
max      6735.000000     409.680000

In [35]:
Reviews["review_score"].value_counts(
    dropna=False
).sort_index()

review_score
1    11424
2     3151
3     8179
4    19142
5    57328
Name: count, dtype: int64